git:
  depth: 3
env:
  global:
  - AWS_DEFAULT_REGION: us-west-1
  - S3_PARAMS: '"--acl public-read --cache-control \"public,must-revalidate,proxy-revalidate,max-age=0\""'
  - JEMALLOC_PARAMS: '"--with-jemalloc-prefix=je_ --disable-stats --disable-fill --disable-cxx
      --disable-initial-exec-tls"'
  - secure: ZSiquC7ipEpfC0UOWARw3kKAYzAFpnVDVN6AaOT8iPO5+9HQTU6cvj/BBjOahZORxM2V6LhVjn709nVLMhhe6/Ib07x/6zVdWdfu7VKr/a5aZNxTFNLBMQw8D9yGh77ku270+60Hx9oNEColi6012C1clrWFSfENAcOMTnSCaYeWkkQVc/R3FaKN7b9WDp1UzO6/qIdp43b/M27H/p1I87pbe8+EcO53lmTQ8WE6Cdf/hp3eufG4IXhjlhYQbvgXwCwG7bouGSPKy0eESmTc96cJwS0zLHg7Ishyp4wPI38EJn9CEM6BmHr0Evx4sGeLknZGwawf6/rZGz/DUJvfq5xB2Q7vCzf77tU1JWQVMJtA/pqBeREBKif6ETV4sRU6YzGfQY4IDv63fM2JysyxFiDImqpX972ePLFdIpuuXvb5VP3Yi+wb/mMROzIist18Q2AeCTkJ5fcMUv2VHjnf+WtwKCc/QvQHtk7QChYawSBbVr4pPpY32KqPOFXuwzd7hU23G53OYU/aMFZYBR967nmReXM5TxNcS5exebw3yiN/6e9RI5F0ZwhhcTlA3nO2dVQBj8YPbWMRRPQzPiMv6nO5XA7Ky3aHIZ41HJOZbZVqzrW/m1Yqpz6K6dBW9d8Dv2ehXriZsdeH+5+Gq4APUr2MmT6zbm+LY0KB+XzyNV0=
matrix:
  include:
  - name: Linux x64
    dist: xenial
    language: c
    compiler: gcc
    addons:
      apt:
        packages:
        - gcc-4.8
    before_install:
    - pip install --user awscli
    - export PATH=$PATH:$HOME/.local/bin
    script:
    - CC=gcc-4.8 CFLAGS="-U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=0" LDFLAGS=-Wl,--wrap,memcpy
      ./autogen.sh $JEMALLOC_PARAMS
    - make
    - cd lib
    - strip libjemalloc.so
    - git log --first-parent --pretty=format:%H HEAD~2..HEAD~1 > revision.git
    - aws s3 cp libjemalloc.so s3://lwjgl-mips64/nightly/linux/x64/libjemalloc.so
      $S3_PARAMS
    - aws s3 cp revision.git s3://lwjgl-mips64/nightly/linux/x64/libjemalloc.so.git
      $S3_PARAMS
  - name: Linux arm32
    dist: xenial
    language: c
    compiler: gcc
    addons:
      apt:
        packages:
        - gcc-4.8-arm-linux-gnueabihf
        - libc6-dev-armhf-cross
    before_install:
    - pip install --user awscli
    - export PATH=$PATH:$HOME/.local/bin
    script:
    - CC=arm-linux-gnueabihf-gcc-4.8 CFLAGS="-U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=0"
      ./autogen.sh --host=arm-linux-gnueabihf $JEMALLOC_PARAMS
    - make
    - cd lib
    - arm-linux-gnueabihf-strip libjemalloc.so
    - git log --first-parent --pretty=format:%H HEAD~2..HEAD~1 > revision.git
    - aws s3 cp libjemalloc.so s3://lwjgl-mips64/nightly/linux/arm32/libjemalloc.so
      $S3_PARAMS
    - aws s3 cp revision.git s3://lwjgl-mips64/nightly/linux/arm32/libjemalloc.so.git
      $S3_PARAMS
  - name: Linux arm64
    dist: xenial
    language: c
    compiler: gcc
    addons:
      apt:
        packages:
        - cmake
        - gcc-4.8-aarch64-linux-gnu
        - libc6-dev-arm64-cross
    before_install:
    - pip install --user awscli
    - export PATH=$PATH:$HOME/.local/bin
    script:
    - CC=aarch64-linux-gnu-gcc-4.8 CFLAGS="-U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=0"
      ./autogen.sh --host=aarch64-linux-gnu $JEMALLOC_PARAMS
    - make
    - cd lib
    - aarch64-linux-gnu-strip libjemalloc.so
    - git log --first-parent --pretty=format:%H HEAD~2..HEAD~1 > revision.git
    - aws s3 cp libjemalloc.so s3://lwjgl-mips64/nightly/linux/arm64/libjemalloc.so
      $S3_PARAMS
    - aws s3 cp revision.git s3://lwjgl-mips64/nightly/linux/arm64/libjemalloc.so.git
      $S3_PARAMS
  - name: Linux mips64
    dist: xenial
    language: c
    compiler: gcc
    addons:
      apt:
        packages:
        - cmake
        - gcc-5-mips64el-linux-gnuabi64
        - libc6-dev-mips64el-cross
    before_install:
    - pip install --user awscli
    - export PATH=$PATH:$HOME/.local/bin
    script:
    - CC=mips64el-linux-gnuabi64-gcc-5 CFLAGS="-U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=0"
      ./autogen.sh --host=mips64el-linux-gnuabi64 $JEMALLOC_PARAMS
    - make
    - cd lib
    - mips64el-linux-gnuabi64-strip libjemalloc.so
    - git log --first-parent --pretty=format:%H HEAD~2..HEAD~1 > revision.git
    - aws s3 cp libjemalloc.so s3://lwjgl-mips64/nightly/linux/mips64/libjemalloc.so
      $S3_PARAMS
    - aws s3 cp revision.git s3://lwjgl-mips64/nightly/linux/mips64/libjemalloc.so.git
      $S3_PARAMS
  - name: macOS
    language: objective-c
    osx_image: xcode11.3
    compiler: clang
    before_install:
    - brew update
    install:
    - brew install awscli
    script:
    - ./autogen.sh $JEMALLOC_PARAMS --disable-zone-allocator EXTRA_CFLAGS="-mmacosx-version-min=10.9"
      EXTRA_CXXFLAGS="-mmacosx-version-min=10.9" LDFLAGS="-mmacosx-version-min=10.9"
    - make
    - cd lib
    - strip -u -r libjemalloc.dylib
    - git log --first-parent --pretty=format:%H HEAD~2..HEAD~1 > revision.git
    - aws s3 cp libjemalloc.dylib s3://lwjgl-mips64/nightly/macosx/x64/libjemalloc.dylib
      $S3_PARAMS
    - aws s3 cp revision.git s3://lwjgl-mips64/nightly/macosx/x64/libjemalloc.dylib.git
      $S3_PARAMS
